### ISSUE TITLE
`記事一覧に戻る`ボタンが動いてなさそう

### ISSUE THREAD

**Issue by vm-xeck** [tuatmcc/homepage2.0#493]
[tuatmcc/hp-md-content](https://github.com/tuatmcc/hp-md-content)リポジトリかも
`news`及び`blog`以下の記事で確認

**Comment by OJII3** [comment]
ありがとうございます


ここらへんですね〜

https://github.com/tuatmcc/homepage2.0/blob/develop/src/components/md/ArticleWrapper/index.tsx

とりあえず直しちゃいます

**Comment by OJII3** [comment]
訂正: CIがこけて面倒くさくなったので明後日以降直します💥🫵😠😩
